# Generated by Django 3.1.1 on 2020-09-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KartaQSL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znak', models.CharField(max_length=20)),
                ('qso_data', models.DateTimeField()),
                ('wyslana', models.BooleanField(default=True)),
                ('odebrana', models.BooleanField(default=False)),
            ],
        ),
    ]
