# Generated by Django 3.1.1 on 2020-09-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartaqsl',
            name='qso_data',
            field=models.DateField(),
        ),
    ]
