# Generated by Django 3.1.1 on 2020-09-28 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KartaQSL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znak', models.CharField(max_length=20)),
                ('qso_data', models.DateField()),
                ('wyslana', models.BooleanField(default=True)),
                ('odebrana', models.BooleanField(default=False)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karty.operator')),
            ],
        ),
    ]
